### ISSUE TITLE
mirror 

### ISSUE THREAD

**Issue by mitomm** [ansteh/shape-json#1]
Hi,
mir ist gerade ein kleiner "Bug" oder eher ein Verbesserungsvorschlag für shape-json aufgefallen.
Falls man beispielsweise folgendes durchführt:

`$mirror[employees](eid)": { ... }
`
und die "eid" null ist, dann kommt momentan sowas:

```
[
   {
     "id": null,
     "name": null,
     "prename": null
   }
]

```

besser wäre doch einfach ein leeres Array [ ] zurück zu geben oder?
Dass die id null ist kommt bei LEFT JOIN mal vor.

**Comment by ansteh** [comment]
proposed feature has been implemented
