### ISSUE TITLE
Scheme with fixed value

### ISSUE THREAD

**Issue by GilVieira** [ansteh/shape-json#4]
Hi, is there any configuration to enter a fixed value in the scheme, for example all objects have a property 'active' = true. For example:

`var scheme = {
  "$group[contributors](pid)": {
    "id": "pid",
    "name": "contributor",
    "active": true, // true in all objects
    "$group[projects](projectID)": {
      "id": "projectID",
      "name": "projectName"
    }
  }
};`

Tks

**Comment by ansteh** [comment]
Hi, 
use this scheme to achieve desired result:

`var scheme = {
      "$group[contributors](pid)": {
        "id": "pid",
        "name": "contributor",
        "$set[active]": true, // true in all objects
        "$group[projects](projectID)": {
          "id": "projectID",
          "name": "projectName"
        }
      }
    };`

P.S.: also added a documentation [https://github.com/ansteh/shape-json#assign-default-values-by-scheme](url) and a test [https://github.com/ansteh/shape-json/blob/master/test/spec/set-value.js](url)
