### ISSUE TITLE
Excel-to-JSON is using shape-json

### ISSUE THREAD

**Issue by he-yang** [ansteh/shape-json#5]
@ansteh 
Excel-to-JSON is using shape json, https://github.com/he-yang/Excel-to-JSON
Thank you for your work.

**Comment by ansteh** [comment]
Thank you for your notice.
One of the greatest pleasures in life is to contribute in some way.

**Comment by jeyakums** [comment]
Great work folks had a few Excel files to convert to JSON and the addin really helped. it becomes very messy to read excel via OleDB
