### ISSUE TITLE
Dont know how to make arrays

### ISSUE THREAD

**Issue by jmdjr** [ansteh/shape-json#8]
I am planning on using this (actually an excel add-in using this system) and was wondering how would you form the syntax of the scheme to generate just an array of values? like 

{
  phrases: ["text1", "text2", "some more text"]
}

**Comment by ansteh** [comment]
Hi @jmdjr,
here an example with the "$set" operator:

```js
'use strict';
const shape = require('shape-json');

let input = { name: 'jmdjr' };

let scheme = {
  "$set": {
    "phrases": ["text1", "text2", "some more text"]
  },
  "name": "name",
};

console.log(shape.parse(input, scheme));
```

```json
{ 
  "phrases": [ "text1", "text2", "some more text" ],
  "name": "jmdjr" 
}
```

I would recommend to pull again. I fixed a bug by the way.
